### ISSUE TITLE
`options.CSL` does not support local file

### ISSUE THREAD

**Issue by chaichontat** [timlrx/rehype-citation#10]
Hi again, I found that setting `options.CSL` to be the path to a local CSL style file did not have any effect. 

A quick digging found that `options.CSL` is read directly into `Cite.plugins.config.get('@csl').engine` without file reading and template addition.

I see that you wrote that we need to add locales or styles using the generator function. However, I did try executing `config.templates.add('nature',  await readFile('https://www.zotero.org/styles/nature'))`
between these two lines
https://github.com/timlrx/rehype-citation/blob/81362c829c4f8f532a17832d898652df5435ef97/src/generator.js#L138-L139
and it seems to work just fine.

Is there a reason why we need to run a generator function beforehand? At least we need to prevent it from failing silently.

**Comment by timlrx** [comment]
Thanks, so it seems that this test over here does not work: https://github.com/timlrx/rehype-citation/blob/main/test/index.js#L89-L96

The reason why I moved adding locales or styles to the the generator function is because I do not really know the name of the style added (e.g. nature) and where the file is coming from (fetch or local), so I decided it was easier to let the user specify it themselves. 

Yes, I should remove that part of the readme and raise an alert.

**Comment by chaichontat** [comment]
Since we know that the built-in styles are `['vancouver', 'harvard1', 'mla', 'chicago'], could we screen for these and pass everything else to the logic that you used to fetch/read `bibliography`?

Do we need to know the name of the style? I could think of one use case: when the user wants to choose a different csl on the frontmatter without writing out the whole path or are there other cases that I'm not aware of.
